- name: change route53
  route53: 
    state: present
    zone: gkread.com
    record: www.gkread.com
    failover: PRIMARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "NEW_ALIAS"
    wait: yes
    health_check: "f4804cc5-f2b1-4e4b-9d31-02d1402c46ab"
